// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufnupdqnwrfdjhqschpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbnVwZHFud3JmZGpocXNjaHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjQ4NTYsImV4cCI6MjA2NDA0MDg1Nn0.GIRcFQX0JzFYYMxQSWswCtrUU_3EtfAJ-tRZuhgaebQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);